version: 0.2

env:
  variables:
    CONTAINER_NAME: "frontend"
    ECR_REPO_NAME: "swiggy-clone-frontend"
    TASK_FAMILY: "swiggy-clone-frontend"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

      - echo Creating taskdef.json from template...
      - sed "s|<IMAGE_URI>|${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}|g" taskdef-template.json > taskdef.json

      - echo "Running Trivy image scan (non-fatal)..."
      - trivy image "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}" > trivyimage.txt || echo "Trivy returned non-zero (logged)"; true

      - echo "Running Dependency-Check (non-fatal)..."
      - if [ -d "./dependency-check/bin" ]; then
          cd dependency-check/bin;
          mkdir -p ../../dependency-check-report;
          # remove invalid flag; dependency-check will auto-update NVD if network allows
          ./dependency-check.sh --scan ../../ -f ALL --out ../../dependency-check-report || echo "dependency-check failed (logged)";
          cd ../../;
        else
          echo "dependency-check not found, skipping";
        fi

      - echo "Uploading scan reports to S3 (if any)..."
      - aws s3 cp ./trivyimage.txt s3://${ARTIFACT_BUCKET}/trivyimage.txt || true
      - if [ -d "./dependency-check-report" ]; then aws s3 cp ./dependency-check-report s3://${ARTIFACT_BUCKET}/ --recursive || true; fi

      - echo "Running SonarQube analysis (only if SONAR_HOST_URL provided)..."
      - |
        if [ -n "$SONAR_HOST_URL" ]; then
          if curl -sSf "$SONAR_HOST_URL" >/dev/null 2>&1; then
            echo "Sonar host reachable, running sonar-scanner..."
            sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_TOKEN" || echo "SonarScanner failed (logged)"
          else
            echo "Sonar host not reachable at $SONAR_HOST_URL — skipping Sonar scan"
          fi
        else
          echo "SONAR_HOST_URL not set — skipping Sonar scan"
        fi

      - echo "Build completed (post_build) — continuing even if scans failed."

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imagedefinitions.json
