version: 0.2

env:
  variables:
    CONTAINER_NAME: "frontend"
    ECR_REPO_NAME: "swiggy-clone-frontend"

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17

  pre_build:
    commands:
      - echo "Detecting AWS account..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_REGION:-$(aws configure get region)}
      - echo "ACCOUNT_ID=$ACCOUNT_ID REGION=$REGION"
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${ECR_REPO_NAME}:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}

      - echo "Generating imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}" > imagedefinitions.json

      - echo "Generating taskdef.json..."
      - sed "s|<IMAGE_URI>|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}|g" taskdef-template.json > taskdef.json

      - echo "Running Trivy image scan (non-fatal)..."
      - trivy image ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG} > trivyimage.txt || true

      - echo "Running OWASP dependency-check (non-fatal)..."
      - cd dependency-check/bin || echo "No dependency-check found, skipping"
      - mkdir -p ../../dependency-check-report || true
      - ./dependency-check.sh --scan ../../ -f ALL --out ../../dependency-check-report || true
      - cd ../../

      - echo "Uploading scan reports to S3..."
      - aws s3 cp trivyimage.txt s3://blue-green-codebuild/trivyimage-${IMAGE_TAG}.txt || true
      - aws s3 cp dependency-check-report s3://blue-green-codebuild/depcheck-${IMAGE_TAG}/ --recursive || true

      - echo "Skipping SonarQube (disabled by default)"

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imagedefinitions.json
